name: 'agribusiness'

services:
  app:
    container_name: agribusiness-app
    image: agribusiness-app
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  postgres:
    container_name: agribusiness-postgres
    image: postgres:16-alpine
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TIMEZONE='America/Sao_Paulo'
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}
    networks:
      - network
    volumes:
      - postgres_db:/var/lib/postgres/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d agribusiness -U postgres' ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  network:
    driver: bridge

volumes:
  postgres_db:
